### ISSUE TITLE
Domain undefined, when making request to Waitlisted.co using an AWS Lambda

### ISSUE THREAD

**Issue by MadsMadsDk** [waitlisted/waitlisted-js#1]
Hi Waitlisted,

I've encountered an issue, where I'm not able to perform any requests using an AWS Lambda, as my domain seems to be undefined. It also happens when I try to invoke the Lambda in development.

It seems I'm missing something - somewhere to tell waitlisted what my waitlisted app-domain is, but I can't find anywhere in the documentation that describes this.

Here's my code:

```typescript
'use strict'
import Waitlisted = require('waitlisted')

let defaultClient = Waitlisted.ApiClient.instance
let api_key = defaultClient.authentications['api_key']
api_key.apiKey = process.env.api_key

let waitlistedApi = new Waitlisted.ReservationApi()

export function handler(event: WaitlistEvent, context: any, callback: (error: any, data: any) => void): void {
  // Load these once to save time and memory

  let body = new Waitlisted.Reservation()
  body.email = event.email
  body.name = event.name
  body.affiliate = event.affiliate

  waitlistedApi.createReservation(body)
    .then(result => {
      var res = { data: result.data }
      callback(null, res)
    })
    .catch(err => {
      callback(err, false)
    })
}

export interface WaitlistEvent {
  email: string
  name?: string
  affiliate?: string
}
```

Produces the following error:

```javascript
error:
      { Error: cannot POST /api/v2/reservations (404)
          at Response.toError (/waitlist-co-integration/node_modules/superagent/lib/node/response.js:106:13)
          at Response.setStatusProperties (/waitlist-co-integration/node_modules/superagent/lib/node/response.js:183:12)
          at new Response (/waitlist-co-integration/node_modules/superagent/lib/node/response.js:42:8)
          at IncomingMessage.<anonymous> (/waitlist-co-integration/node_modules/superagent/lib/node/index.js:1042:22)
          at emitNone (events.js:91:20)
          at IncomingMessage.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:974:12)
          at _combinedTickCallback (internal/process/next_tick.js:74:11)
          at process._tickCallback (internal/process/next_tick.js:98:9)
        status: 404,
        text: '{"errors":["Unknown Site"]}',
        method: 'POST',
        path: '/api/v2/reservations' }
```

So what should I do to make sure `domain` isn't `null`?

**Comment by j-mcnally** [comment]
Try setting basePath as demo is here


https://github.com/waitlisted/waitlisted-client-examples/tree/master/nodejs

**Comment by MadsMadsDk** [comment]
That did the trick. Thanks! :)
